### ISSUE TITLE
Use of `std::process::abort` is potentially unsound

### ISSUE THREAD

**Issue by nagisa** [Sgeo/take_mut#12]
`std::process::abort` might fail to terminate the program if the signal is caught and the handler `longjmp`s away. While `longjmp` is a poorly supported feature in Rust, it is nevertheless something that [is valid to do](https://www.man7.org/linux/man-pages/man3/abort.3.html#DESCRIPTION).

**Comment by Sgeo** [comment]
Would switching back to exit be sufficient to resolve this? If I'm reading manuals properly, attempting to longjmp from a place that can interfere with exit is undefined.

**Comment by Sgeo** [comment]
Discussion in the Rust discord makes me believe `longjmp` is currently considered to be usually unsound in Rust.

**Comment by Sgeo** [comment]
Might be worth keeping an eye on https://github.com/rust-lang/rfcs/issues/2625
