### ISSUE TITLE
Use std::process::abort instead of std::process::exit

### ISSUE THREAD

**Issue by sugar700** [Sgeo/take_mut#6]
This allows debuggers to catch abnormal termination and provides better information for shells about why process quit (due to SIGABRT signal). `std::process::exit` is hardly one.

**Comment by Sgeo** [comment]
This is already planned for the next version of take_mut: https://github.com/Sgeo/take_mut/commit/80ddae0dab6e86e32e8d82b439fd1eaa3f61a0b2

Just need to get around to adding documentation and tests for other new features.
